### ISSUE TITLE
Add Method to Fetch Latest Team Responses and Sort by Reviewer Name

### ISSUE THREAD

**Issue by AnuragGorkar** [MakarandPundlik/reimplementation-back-end#2]
Implement methods to retrieve the latest response for a specific team, sorted by the reviewer's name. The `assessments_for` method should handle retrieval for a given team and invoke helper methods to collect valid responses and sort them by reviewer name. Ensure that the code filters out empty or unsubmitted responses to maintain data quality. Write corresponding tests to validate each method’s functionality and sorting behavior.

**Comment by Rutvik2598** [comment]
1. Added a method to fetch latest response for a specific team in response_map.rb file.
   - Commit for reference: https://github.com/MakarandPundlik/reimplementation-back-end/commit/24db89793f2c60743f7856cf52daa57c71783f38
   
2. Added tests in the response_map_spec.rb file to test the assessments_for method results
   - Commit for reference: https://github.com/MakarandPundlik/reimplementation-back-end/commit/9d3bb41298ca71f4aa9771761871b596c1a1da91

**Comment by AnuragGorkar** [comment]
Implementation of the functions are correct and the 2 added tests are running correctly:
![Image](https://github.com/user-attachments/assets/c1c10b72-e282-48e5-8795-be37555268f4)
