### ISSUE TITLE
Add Method to Retrieve Latest Responses from a Specific Reviewer for a Given Team

### ISSUE THREAD

**Issue by Rutvik2598** [MakarandPundlik/reimplementation-back-end#3]
- Create a method to retrieve latest responses from a specific reviewer for a given team.

**Comment by AnuragGorkar** [comment]
Add the features and tests in the following commits: 
Features commit: [Added latest responses for team by a reviewer](https://github.com/expertiza/reimplementation-back-end/commit/bd78a219d446c7366bf37578f201747610905161)
Test commit: [Added test for latest review for team by reviewer](https://github.com/expertiza/reimplementation-back-end/commit/5e8e71eb71cf6af930a09f489555e55806d1587b)

**Comment by Rutvik2598** [comment]
- The changes looks good to me.
- Tests are running and passing as expected.
