### ISSUE TITLE
Add Method to Fetch All Responses Submitted by a Specific Reviewer

### ISSUE THREAD

**Issue by AnuragGorkar** [MakarandPundlik/reimplementation-back-end#4]
Implement methods to retrieve all responses submitted by a given reviewer. The `responses_by_reviewer` method should handle fetching responses linked to a specific reviewer and use helper methods to filter and return only submitted responses. Ensure the `fetch_submitted_responses` method includes only responses that have been marked as submitted, using `process_response_by_type` to handle map types correctly. Add corresponding tests to confirm the accuracy and completeness of the responses retrieved for each reviewer.

**Comment by MakarandPundlik** [comment]
Changes have been added for requested feature. 
Added unit test cases using RSpec as well.
All previous and current unit test cases are passing 

![image](https://github.com/user-attachments/assets/e46dae1b-628f-4497-abd8-fe60a997232b)

**Comment by AnuragGorkar** [comment]
Test cases verified and code logic is correct
