### ISSUE TITLE
Add instance methods for getting assignments and count

### ISSUE THREAD

**Issue by MakarandPundlik** [MakarandPundlik/reimplementation-back-end#5]
Retrieves the assignment associated with the reviewer's team and method to return the count of responses associated with this response map.

**Comment by Rutvik2598** [comment]
- Added changes to implement the instance method to return the count and assignment.
  - [Commit link](https://github.com/MakarandPundlik/reimplementation-back-end/commit/101e20fcd46cb71169d9aa74776814a4f50e04ef)
- Added tests to verify the implemented functions return the correct response.
  - [Commit link](https://github.com/MakarandPundlik/reimplementation-back-end/commit/337c9923f3057e2dc84a7467d2a8aa493954cd1d)

![Image](https://github.com/user-attachments/assets/ad6fcad0-db2b-407d-be28-0b29e5e2165c)
