### ISSUE TITLE
Create a method to find all responses for assignment.

### ISSUE THREAD

**Issue by MakarandPundlik** [MakarandPundlik/reimplementation-back-end#6]
Create a method to return all the responses associated with the specific assignment. Also, create a method which returns latest responses for all teams irrespective of the reviewers.

**Comment by AnuragGorkar** [comment]
Refer the following commits for the feature and testing:
[Feature Commit](https://github.com/expertiza/reimplementation-back-end/commit/a25b9027ba152bedd85cbc6c0d16362534cd79e0)
[Test Code](https://github.com/expertiza/reimplementation-back-end/commit/58ad98c7e5b51ef1e4be772b2177f59215b3f513)

**Comment by AnuragGorkar** [comment]
![Image](https://github.com/user-attachments/assets/e1817411-87c8-42df-98ec-4a951c6fb5cd)
All test cases passed

**Comment by MakarandPundlik** [comment]
Please update the response_map_spec.rb file contents to unit test cases. It was overwritten accidently.

**Comment by AnuragGorkar** [comment]
Added appropriate code to the response_map_spec.rb file. Corrections made successfully
