### ISSUE TITLE
Refactoring the response_map model and test file  

### ISSUE THREAD

**Issue by AnuragGorkar** [MakarandPundlik/reimplementation-back-end#7]
Need to refactor the model for the response_map to ensure appropriate functions are made class methods and assigned as private. Need to add and verify comments. Testing file needs to be refactored for better readability.

Also create and merge PR to main branch and resolve conflicts if any.

**Comment by MakarandPundlik** [comment]
All unit test cases passing after refactoring 
![image](https://github.com/user-attachments/assets/2e8ba6d3-c6e0-41ba-af4b-f3058ad77337)

**Comment by MakarandPundlik** [comment]
Removed unnecessary comments and description. Good to merge with main
